/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resultmanagement;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author acer
 */
public class Marks extends javax.swing.JFrame {

    /**
     * Creates new form Marks
     */
    public Marks() {
        initComponents();
        viewMarks();
    }

    public void viewMarks(){
        try{
              ResultSet rst=DBMS.search("Select studentID, SAD, DM, RAD, Stat, BPM, Graphic, BPR from student");
              resultTable.setModel(DbUtils.resultSetToTableModel(rst));
        }
        catch(Exception e){
              JOptionPane.showMessageDialog(null, "Connection Error");
        }
        resultTable.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SIDText = new javax.swing.JTextField();
        dmText = new javax.swing.JTextField();
        bprText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        graText = new javax.swing.JTextField();
        bpmText = new javax.swing.JTextField();
        statText = new javax.swing.JTextField();
        radText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sadText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 660));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Results");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 270, 40));

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "SAD", "DM", "RAD", "Stat", "BPM", "Graphic", "BPR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        resultTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                resultTableComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(resultTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 790, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("DM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Stat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        SIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIDTextActionPerformed(evt);
            }
        });
        jPanel1.add(SIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, 30));

        dmText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmTextActionPerformed(evt);
            }
        });
        jPanel1.add(dmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 110, 30));

        bprText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprTextActionPerformed(evt);
            }
        });
        jPanel1.add(bprText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 110, 30));

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchButton.setPreferredSize(new java.awt.Dimension(83, 25));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.setMaximumSize(new java.awt.Dimension(83, 25));
        deleteButton.setPreferredSize(new java.awt.Dimension(83, 25));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, -1, -1));

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateButton.setPreferredSize(new java.awt.Dimension(83, 25));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, -1, -1));

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetButton.setText("Reset");
        resetButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetButton.setPreferredSize(new java.awt.Dimension(83, 25));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, -1, -1));

        graText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graTextActionPerformed(evt);
            }
        });
        jPanel1.add(graText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 110, 30));

        bpmText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpmTextActionPerformed(evt);
            }
        });
        jPanel1.add(bpmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 110, 30));

        statText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statTextActionPerformed(evt);
            }
        });
        jPanel1.add(statText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 110, 30));

        radText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTextActionPerformed(evt);
            }
        });
        jPanel1.add(radText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("BPM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Graphic");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("BPR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("RAD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("SAD");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        sadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadTextActionPerformed(evt);
            }
        });
        jPanel1.add(sadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_resultTableComponentShown

    }//GEN-LAST:event_resultTableComponentShown

    private void SIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIDTextActionPerformed

    private void bprTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bprTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try{
            String id=SIDText.getText();
            ResultSet rst=DBMS.search("Select * from course where courseid='"+id+"'");
            if(rst.next()){
                dmText.setText(rst.getString("coursename"));
                bprText.setText(rst.getString("credit"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Record not found");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try{
            String id=SIDText.getText();
            DBMS.iud("Delete from student where studentID='"+id+"'");
            viewMarks();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try{
            String id=SIDText.getText();
            float sad=Float.parseFloat(sadText.getText());
            float dm=Float.parseFloat(dmText.getText());
            float rad=Float.parseFloat(radText.getText());
            float stat=Float.parseFloat(statText.getText());
            float bpm=Float.parseFloat(bpmText.getText());
            float gra=Float.parseFloat(graText.getText());
            float bpr=Float.parseFloat(bprText.getText());
        
            ResultSet rst=DBMS.search("Select * from student where studentID='"+id+"'");
            if(rst.next()){
                DBMS.iud("Update student set SAD='"+sad+"', DM='"+dm+"', RAD='"+rad+"', Stat=='"+stat+"', BPM='"+bpm+"', Graphic='"+gra+"', BPR='"+bpr+"' where studentID='"+id+"'");
                viewMarks();
                JOptionPane.showMessageDialog(null, "Added Successfully");
            }
            else{
                JOptionPane.showMessageDialog(null, "Record not found");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        SIDText.setText("");
        sadText.setText("");
        dmText.setText("");
        radText.setText("");
        statText.setText("");
        bpmText.setText("");
        graText.setText("");
        bprText.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void graTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graTextActionPerformed

    private void bpmTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpmTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpmTextActionPerformed

    private void statTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statTextActionPerformed

    private void radTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radTextActionPerformed

    private void dmTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dmTextActionPerformed

    private void sadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sadTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SIDText;
    private javax.swing.JTextField bpmText;
    private javax.swing.JTextField bprText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dmText;
    private javax.swing.JTextField graText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField radText;
    private javax.swing.JButton resetButton;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextField sadText;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField statText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
